### ISSUE TITLE
Support for Axon 4.3

### ISSUE THREAD

**Issue by YuriyBarvenko1234** [AxonFramework/extension-springcloud#16] opened 2020-03-09 12:17 UTC
Hallo people, I saw that Axon 4.3 is released and the changes for 4.3 in the extension are also in the master branch. But I didn't find any a 4.3 release of extension-springcloud in maven repo. do you have a plan to release 4.3 soon?

thx. a lot.

**Comment by smcvb** [comment] 2020-03-09 12:46
The extension's are always a bit behind, as they rely on the framework release.
On top of that, we are tremendously busy with other projects as well, giving a slightly lower priority to the extensions. 

Know that we did notice your question on #13, it's just that we have a lot of other things to do.

As this is not a bug, feature request or enhancement suggestion, I will be closing this question immediately. All I can ask you now @YuriyBarvenko1234, is to have patience.

**Closed by smcvb** 2020-03-09 12:46 UTC
