### ISSUE TITLE
Spring Cloud DistributedCommandBus Can't Get The True Exception

### ISSUE THREAD

**Issue by e-sen** [AxonFramework/extension-springcloud#7] opened 2019-05-08 12:51 UTC
Hi,User the Spring Cloud DistributedCommandBus I can't get the true exception.

This is the [demo](https://github.com/e-sen/axon-spring-cloud-demo)

I will get org.axonframework.messaging.RemoteHandlingException, not my custom exception.

## Env

> AxonFrameworkVersion: 4.1.1
> AxonFramework-Extension-SpringCloud Version: 4.1
> JDK:Java8

**Comment by smcvb** [comment] 2019-05-15 09:21
This is a correct assumption from your part @e-sen. 
Currently, we only pull the causes out of your custom exception and populate those in the `RemoteHandlingException#exceptionDescriptions` field.

We've noticed this exact same problem for users of the Axon Server approach, for which we have an [issue](https://github.com/AxonFramework/AxonFramework/issues/1079) and [solution](https://github.com/AxonFramework/AxonFramework/pull/1080) in flight.
@abuijze describes the envisioned solution for your problem in the issue description, which I'd argue is also a good solution when users of the `DistributedCommandBus`.

However, that makes this issue not a Spring Cloud Extension specific problem, but a general `DistributedCommandBus` problem. As such, I will be closing this issue.

Regardless, thanks for filing it @e-sen!
I assume you'd agree with the proposed solution in Axon Framework issue [#1079](https://github.com/AxonFramework/AxonFramework/issues/1079)?

**Closed by smcvb** 2019-05-15 09:21 UTC
